# Generated by Django 2.1.5 on 2019-01-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_shop', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
