# Generated by Django 2.1.5 on 2019-01-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_shop', '0003_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='date_churned',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='icecream',
            name='featured',
            field=models.BooleanField(null=True),
        ),
    ]
